### ISSUE TITLE
trim() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by mikk150** [alexeevdv/yii2-health#1]
`alexeevdv\yii\health\Module::$defaultRoute` has to be string not array

https://www.yiiframework.com/doc/api/2.0/yii-base-module#$defaultRoute-detail

**Comment by alexeevdv** [comment]
Fixed in https://github.com/alexeevdv/yii2-health/commit/41168c5a9241e2a457993edba69f298f972e0c9a
